### ISSUE TITLE
发送消息疑问🤔️

### ISSUE THREAD

**Issue by SuKaiFei** [Hurricanezwf/rabbitmq-go#1]
发送时必须指定一个队列名称吗，怎么能不指定队列名称发送消息？

**Comment by Hurricanezwf** [comment]
如果想要不指定队列名称发送消息，需要自己再封装一层针对业务定制的MQ包，这个包里需要自定义整个MQ消息包的封包解包的方式以及对消息内容的编解码方式 以适应实际情况的需要。   
我这里有个使用的代码片段，可以参考下：https://gist.github.com/Hurricanezwf/9eb053afeb19058de83eda191056d371
